// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteComicFromDatabase(arg1:number):Promise<void>;

export function GetComicsFromDatabase():Promise<Array<Record<string, any>>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImageData(arg1:string):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function SearchComicsInDatabase(arg1:string):Promise<Array<Record<string, any>>>;
