// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteComicFromDatabase(arg1) {
  return window['go']['main']['App']['DeleteComicFromDatabase'](arg1);
}

export function GetComicsFromDatabase() {
  return window['go']['main']['App']['GetComicsFromDatabase']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function SearchComicsInDatabase(arg1) {
  return window['go']['main']['App']['SearchComicsInDatabase'](arg1);
}
